import RAGCore

// Contextual retrieval, per-article approximation: a context prefix prepended to each chunk's
// text FOR EMBEDDING ONLY. The stored `Chunk.text` stays raw, so packing, `[Source: Title]`
// citations, and the faithfulness validator are all unaffected — only the embedded vector carries
// the extra context. Queries are still embedded with no prefix. `.none` reproduces the original
// behavior exactly; the two other strategies form an ablation ladder (static title vs LLM-written).
public struct ChunkContextStrategy: Sendable {

    public let name: String
    let prefix: @Sendable (Article) -> String

    public init(name: String, prefix: @escaping @Sendable (Article) -> String) {
        self.name = name
        self.prefix = prefix
    }

    // No prefix — embedded text is the raw chunk. Default, current behavior.
    public static let none = ChunkContextStrategy(name: "none") { _ in "" }

    // Static template, no LLM: every chunk of an article is prefixed with its title.
    public static let title = ChunkContextStrategy(name: "title") { "Article: \($0.title)." }

    // LLM-written 1-2 sentence description per article, looked up by title (generated by
    // RAGContextualizer). Articles missing a description fall back to no prefix.
    public static func fm(_ descriptions: [String: String]) -> ChunkContextStrategy {
        ChunkContextStrategy(name: "fm") { descriptions[$0.title] ?? "" }
    }
}
